#!/usr/bin/env python3
"""Export clean NN C headers from approved checkpoints."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

import numpy as np
import torch

REPO = Path(__file__).resolve().parents[2]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from cfd_applications_cleanroom.cfd_apps.hashes import sha256_file  # noqa: E402
from evaluate.shared import validate_feature_transform  # noqa: E402


OUT_DIR = REPO / "cfd_applications_cleanroom/nn/generated"
CHECKPOINTS = {
    "nn27_r128": (
        REPO / "out/128/baseline_128_hgradient.pt",
        "nn_weights_nn27_r128_clean.h",
    ),
    "nn27_r256": (
        REPO / "out/256/baseline_256_hgradient.pt",
        "nn_weights_nn27_r256_clean.h",
    ),
}


def g(value: float) -> str:
    return f"{float(value):.17g}"


def c_vec(name: str, values: np.ndarray, size: str) -> str:
    arr = np.asarray(values, dtype=np.float64).reshape(-1)
    return f"static const double {name}[{size}] = {{{', '.join(g(v) for v in arr)}}};"


def c_mat(name: str, values: np.ndarray, rows: str, cols: str) -> str:
    arr = np.asarray(values, dtype=np.float64)
    chunks = ["{" + ", ".join(g(v) for v in row) + "}" for row in arr]
    return f"static const double {name}[{rows}][{cols}] = {{{', '.join(chunks)}}};"


def export_checkpoint(label: str, checkpoint: Path, header_name: str) -> dict[str, Any]:
    bundle = torch.load(checkpoint, map_location="cpu", weights_only=False)
    transform = validate_feature_transform(bundle["feature_transform"])
    input_dim = int(bundle["model_config"]["input_dim"])
    raw_dim = int(transform["raw_feature_dim"])
    output_dim = int(transform["output_dim"])
    hidden = int(bundle["model_config"]["hidden_units"])
    if input_dim != 27 or raw_dim != 27 or output_dim != 27:
        raise ValueError(f"{checkpoint} is not a clean 27D raw27 checkpoint")
    if transform["feature_order"] != "phi9+nx9+ny9":
        raise ValueError(f"{checkpoint} has unexpected feature order {transform['feature_order']!r}")

    sd = bundle["state_dict"]

    def weight(key: str) -> np.ndarray:
        return np.asarray(sd[key].detach().cpu().numpy(), dtype=np.float64)

    mean = np.asarray(transform["mean"], dtype=np.float64)
    std = np.asarray(transform["std"], dtype=np.float64)
    lines = [
        "#pragma once",
        "/* GENERATED by export_clean_nn_assets.py. Do not edit by hand. */",
        f"/* checkpoint: {checkpoint.relative_to(REPO).as_posix()} */",
        "#define RAW_IN 27",
        "#define MLP_IN 27",
        f"#define MLP_H {hidden}",
        c_vec("MEAN", mean, "RAW_IN"),
        c_vec("STD", std, "RAW_IN"),
        c_mat("W0", weight("net.0.weight"), "MLP_H", "MLP_IN"),
        c_vec("b0", weight("net.0.bias"), "MLP_H"),
        c_mat("W1", weight("net.2.weight"), "MLP_H", "MLP_H"),
        c_vec("b1", weight("net.2.bias"), "MLP_H"),
        c_mat("W2", weight("net.4.weight"), "MLP_H", "MLP_H"),
        c_vec("b2", weight("net.4.bias"), "MLP_H"),
        c_mat("W3", weight("net.6.weight"), "MLP_H", "MLP_H"),
        c_vec("b3", weight("net.6.bias"), "MLP_H"),
        c_mat("W4", weight("net.8.weight"), "1", "MLP_H"),
        c_vec("b4", weight("net.8.bias"), "1"),
    ]
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    header = OUT_DIR / header_name
    header.write_text("\n\n".join(lines) + "\n")
    return {
        "label": label,
        "checkpoint_path": checkpoint.relative_to(REPO).as_posix(),
        "checkpoint_sha256": sha256_file(checkpoint),
        "weights_header": header.relative_to(REPO).as_posix(),
        "weights_header_sha256": sha256_file(header),
        "input_dim": input_dim,
        "raw_feature_dim": raw_dim,
        "target": "h*kappa",
        "feature_order": "phi9+nx9+ny9",
        "hidden_units": hidden,
        "seed": bundle["model_config"].get("seed"),
    }


def export_all() -> dict[str, Any]:
    rows = [
        export_checkpoint(label, checkpoint, header)
        for label, (checkpoint, header) in CHECKPOINTS.items()
    ]
    manifest = {
        "exporter": "cfd_applications_cleanroom/nn/export_clean_nn_assets.py",
        "input_dim": 27,
        "normalization": "z=(raw27-mean)/std from checkpoint feature_transform",
        "target_definition": "h*kappa",
        "architecture": "MLP 27-128-128-128-128-1 ReLU",
        "stencil_order": [
            [-1, 1],
            [0, 1],
            [1, 1],
            [-1, 0],
            [0, 0],
            [1, 0],
            [-1, -1],
            [0, -1],
            [1, -1],
        ],
        "rows": rows,
    }
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    manifest_path = OUT_DIR / "export_manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    return manifest


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--print-json", action="store_true")
    args = parser.parse_args()
    manifest = export_all()
    if args.print_json:
        print(json.dumps(manifest, indent=2, sort_keys=True))
    else:
        print("export_manifest=cfd_applications_cleanroom/nn/generated/export_manifest.json")
        print(f"exported_headers={len(manifest['rows'])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
